"""add platform active and auditmixin attempt

Revision ID: 10c7225d7b8f
Revises: aa9929826d76
Create Date: 2022-03-14 22:25:31.606574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10c7225d7b8f'
down_revision = 'aa9929826d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditmixin',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('platforms', sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'is_active')
    op.drop_table('auditmixin')
    # ### end Alembic commands ###
