"""actually add ubereats db model

Revision ID: 31476eb20647
Revises: eaae8700d9e1
Create Date: 2022-03-16 00:29:08.938709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31476eb20647'
down_revision = 'eaae8700d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uberorders',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('order_or_refund_date', sa.Date(), nullable=True),
    sa.Column('order_accept_time', sa.Time(), nullable=True),
    sa.Column('food_sales_excl_vat', sa.Float(), nullable=True),
    sa.Column('food_sales_incl_vat', sa.Float(), nullable=True),
    sa.Column('delivery_fee_incl_vat', sa.Float(), nullable=True),
    sa.Column('total_order_incl_vat', sa.Float(), nullable=True),
    sa.Column('cost_of_delivery_incl_vat', sa.Float(), nullable=True),
    sa.Column('gratuity', sa.Float(), nullable=True),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('payout_date', sa.Date(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('platform_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uberorders')
    # ### end Alembic commands ###
