"""remove loyverse_orders receipt unique contraint

Revision ID: 44e433255140
Revises: 7b9d6dfe061c
Create Date: 2022-03-16 16:19:14.365364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e433255140'
down_revision = '7b9d6dfe061c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('loyverse_orders_receipt_number_key', 'loyverse_orders', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('loyverse_orders_receipt_number_key', 'loyverse_orders', ['receipt_number'])
    # ### end Alembic commands ###
