"""add unique constraint to mrd invoice number

Revision ID: 4b5c58b3962e
Revises: 157a6ff402de
Create Date: 2022-03-15 23:32:02.617068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5c58b3962e'
down_revision = '157a6ff402de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mrdorders', ['invoice_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mrdorders', type_='unique')
    # ### end Alembic commands ###
