"""remove backpolultes mrdorders

Revision ID: 4d98743b4e48
Revises: 10c7225d7b8f
Create Date: 2022-03-14 22:41:50.346212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d98743b4e48'
down_revision = '10c7225d7b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
