"""add loyverseorders table

Revision ID: 71e06f1fe5d9
Revises: 31476eb20647
Create Date: 2022-03-16 14:06:23.754587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e06f1fe5d9'
down_revision = '31476eb20647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
