"""add timezone to uber order accept time

Revision ID: 84fd6813ccf9
Revises: 946c09e6f5bf
Create Date: 2022-03-16 18:44:08.246009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84fd6813ccf9'
down_revision = '946c09e6f5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uber_orders', 'order_accept_time',
               existing_type=postgresql.TIME(),
               type_=sa.Time(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uber_orders', 'order_accept_time',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
