"""add unique contraints to model inherited order ids

Revision ID: 86353543b8ac
Revises: f9423bee1477
Create Date: 2022-03-16 15:47:31.291467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86353543b8ac'
down_revision = 'f9423bee1477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'loyverseorders', ['receipt_number'])
    op.create_unique_constraint(None, 'uberorders', ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uberorders', type_='unique')
    op.drop_constraint(None, 'loyverseorders', type_='unique')
    # ### end Alembic commands ###
