"""add default to mrdorders table id column

Revision ID: 86dfd551c936
Revises: 7c2916af748a
Create Date: 2022-03-15 22:04:28.273798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dfd551c936'
down_revision = '7c2916af748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
