"""add id column from mrdorders table

Revision ID: 924619910053
Revises: 22d101f279a0
Create Date: 2022-03-15 22:19:28.667711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924619910053'
down_revision = '22d101f279a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
