"""add workflow_id column to uber_orders table

Revision ID: 946c09e6f5bf
Revises: 98d36a8586d4
Create Date: 2022-03-16 18:22:13.962682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '946c09e6f5bf'
down_revision = '98d36a8586d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uber_orders', sa.Column('workflow_id', postgresql.UUID(), nullable=True))
    op.drop_constraint('uber_orders_order_id_key', 'uber_orders', type_='unique')
    op.create_unique_constraint(None, 'uber_orders', ['workflow_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uber_orders', type_='unique')
    op.create_unique_constraint('uber_orders_order_id_key', 'uber_orders', ['order_id'])
    op.drop_column('uber_orders', 'workflow_id')
    # ### end Alembic commands ###
