"""Initial migration

Revision ID: afdd63ae7a65
Revises: b1cf65ef30cf
Create Date: 2022-02-23 16:45:46.814765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdd63ae7a65'
down_revision = 'b1cf65ef30cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
