"""Refactor File model to FileMap

Revision ID: b1cf65ef30cf
Revises: 2ce6d7eb2a38
Create Date: 2021-08-14 11:22:09.436545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1cf65ef30cf'
down_revision = '2ce6d7eb2a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filemap',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filemap_id'), 'filemap', ['id'], unique=False)
    op.create_index(op.f('ix_filemap_name'), 'filemap', ['name'], unique=False)
    op.drop_index('ix_file_id', table_name='file')
    op.drop_index('ix_file_name', table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='file_pkey')
    )
    op.create_index('ix_file_name', 'file', ['name'], unique=False)
    op.create_index('ix_file_id', 'file', ['id'], unique=False)
    op.drop_index(op.f('ix_filemap_name'), table_name='filemap')
    op.drop_index(op.f('ix_filemap_id'), table_name='filemap')
    op.drop_table('filemap')
    # ### end Alembic commands ###
