"""add is_processed column to platform order models

Revision ID: e681f40439bb
Revises: 84fd6813ccf9
Create Date: 2022-03-17 20:33:46.491682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e681f40439bb'
down_revision = '84fd6813ccf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyverse_orders', sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('mrd_orders', sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('uber_orders', sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uber_orders', 'is_processed')
    op.drop_column('mrd_orders', 'is_processed')
    op.drop_column('loyverse_orders', 'is_processed')
    # ### end Alembic commands ###
