"""add ubereats db model

Revision ID: eaae8700d9e1
Revises: 4b5c58b3962e
Create Date: 2022-03-16 00:26:46.576579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaae8700d9e1'
down_revision = '4b5c58b3962e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
